### ISSUE TITLE
you are not tracking user's task

### ISSUE THREAD

**Issue by mr-abims** [olahfemi/To-Do-Contract#1]
https://github.com/olahfemi/To-Do-Contract/blob/9e4fa15edaaf23416eb97c2fd9b7e3f61b26bae4/contracts/To-Do.sol#L1

**Comment by olahfemi** [comment]
I'm not sure I understand the issue, but I think I am. The task is supposed to be the string "item". I'm capturing each with a struct.  

Please let me know if I'm missing the point of your message. Thanks.

**Comment by olahfemi** [comment]
I'm not sure I understand the issue, but I think I am. The task is supposed to be the string "item". I'm capturing each with a struct.

Please let me know if I'm missing the point of your message. Thanks.
